version: "3"

services: 
  rabbitMQ:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SQWBNTRESLKUU'
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
    ports: 
     - "8080:15672"
     - "5672:5672"
      
